### ISSUE TITLE
结合sequelize-typescript写是不是更好？

### ISSUE THREAD

**Issue by zlq4863947** [demopark/sequelize-docs-Zh-CN#2]
现在ts比较火，用的人比较多。
我的话就是用sequelize-typescript来使用sequelize。
所有我感觉如果结合sequelize-typescript一起写中文文档会更好一点
sequelize-typescript地址：https://github.com/RobinBuschmann/sequelize-typescript

**Comment by demopark** [comment]
sequelize 封装库太多, 暂时只维护官方文档. 如官方加入 TS 支持, 则会进一步更新文档.
