### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by keenwon** [demopark/sequelize-docs-Zh-CN#22]
https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/scopes.md#%E5%85%B3%E8%81%94

> 举个例子，思考模型Post和Comment。 注释与其他几个模型（图像，视频等）相关联，注释和其他模型之间的关联是多态的，这意味着除了外键 commentable_id 之外，注释还存储一个commentable列。

Post & Comment 应该是帖子和评论吧？

**Comment by keenwon** [comment]
https://en.wikipedia.org/wiki/Comment_(computer_programming)

感觉只有在代码中才是翻译为“注释”

**Comment by demopark** [comment]
此处的Comment不应被翻译，已修正
