### ISSUE TITLE
请问最新版本是否还支持老的嵌套函数回调的方法？

### ISSUE THREAD

**Issue by yinguangluoren** [demopark/sequelize-docs-Zh-CN#3]
请问最新的4.28.6 是否还支持
类似于
sequelizer.findAll("user",{where: {name:"zhangsan"}}, function(err, result {
       //callback
}))这样的方法

**Comment by demopark** [comment]
```
Project.findAll().then(projects => {
  // projects 将是所有 Project 实例的数组
})
```
原有的 then 方法仍然是支持的
看官方意思 建议在 async 函数中 使用 await 获取结果, 并加入事务控制.
