### ISSUE TITLE
文档中关于导入的示例有错

### ISSUE THREAD

**Issue by meltifa** [demopark/sequelize-docs-Zh-CN#36]
https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/models-definition.md#%E5%AF%BC%E5%85%A5

这部分示例代码

`sequelize.import('project', (sequelize, DataTypes) => {
  class Project extends sequelize.Model {}
  Project.init({
    name: DataTypes.STRING,
    description: DataTypes.TEXT
  }, { sequelize })
  return Project;
})`

实际运行会报错，应该使用sequelize.define方法，参考官方示例
https://github.com/sequelize/express-example/tree/master/models

**Comment by demopark** [comment]
你好,5.0之前版本定义模型使用define方法,5.0版本以后使用init. 你给的实例项目是2年前写的,当时使用的sequelize版本为"3.23.6", 建议参考对应版本文档.
