### ISSUE TITLE
 seq.authenticate()

### ISSUE THREAD

**Issue by xgAnd** [demopark/sequelize-docs-Zh-CN#37]
默认情况下,Sequelize 将保持连接打开状态,并对所有查询使用相同的连接. 
我这边连接走了成功的回调并被挂起 但是10秒左右连接被自动关闭了。请问这是正常的嘛，不是持续保持嘛？
"sequelize": "^5.21.5"
"mysql2": "^2.1.0",

**Comment by demopark** [comment]
authenticate是sequelize实例后的内建验证方法, 通过 query 一个简单的 'SELECT 1+1 AS result' 语句来验证连通性.在验证结束后无任何操作,10秒node便会结束当前任务, 并不是connection被关闭. 设置一个setInterval试试,连到天荒地老😃

**Comment by xgAnd** [comment]
> authenticate是sequelize实例后的内建验证方法, 通过 query 一个简单的 'SELECT 1+1 AS result' 语句来验证连通性.在验证结束后无任何操作,10秒node便会结束当前任务, 并不是connection被关闭. 设置一个setInterval试试,连到天荒地老😃

多谢老哥 解惑。
