### ISSUE TITLE
翻译错误（船和船长）

### ISSUE THREAD

**Issue by nimingan** [demopark/sequelize-docs-Zh-CN#38]
[Associations - 关联：基本的涉及关联的查询](https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/core-concepts/assocs.md#基本的涉及关联的查询)

> 为了研究这一点,我们将思考一个例子,其中有船长和船长,.

船长和船长 ---> 船和船长
原文：
[Basics of queries involving associations](https://sequelize.org/master/manual/assocs.html)
In order to study this, we will consider an example in which we have Ships and Captains,

**Comment by demopark** [comment]
感谢指正
