### ISSUE TITLE
文档文案代码示例错误

### ISSUE THREAD

**Issue by huchaolin** [demopark/sequelize-docs-Zh-CN#39]
这里“ 如果你不需要联结表中的任何内容,则可以显式地为 attributes 参数提供一个空数组,在这种情况下,将不会获取任何内容,甚至不会创建额外的属性：

Foo.findOne({
  include: {
    model: Bar,
    attributes: []
  }
});   ”

代码 应改为Foo.findOne({
  include: {
    model: Bar,
    through: {
      attributes: []
    }
  }
});

**Comment by demopark** [comment]
```
Foo.findAll({
  include: [{
    model: Bar,
    through: {
      attributes: [/* 在此处列出所需的属性 */]
    }
  }]
});
```
 对应
```
{
  "id": 1,
  "name": "foo",
  "Bars": [
    {
      "id": 1,
      "name": "bar"
    }
  ]
}
```

======

```
Foo.findOne({
  include: {
    model: Bar,
    attributes: []
  }
});
```
对应
```
{
  "id": 1,
  "name": "foo"
}
```
