### ISSUE TITLE
某句话翻译不贴切 “Constraints & Circularities - 约束 & 循环”

### ISSUE THREAD

**Issue by nimingan** [demopark/sequelize-docs-Zh-CN#43]
[Constraints & Circularities - 约束 & 循环](https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/other-topics/constraints-and-circularities.md#constraints--circularities---约束--循环)
## 不受限制地强制执行外键引用
> 有时,你可能希望引用另一个表,而不添加任何约束或关联. 在这种情况下,你可以将引用属性手动添加到架构定义中,并标记它们之间的关系.

架构定义？ 感觉这里翻译成“模型定义”会贴切一些。

原文：
[Constraints & Circularities](url)
> Sometimes you may want to reference another table, without adding any constraints, or associations. In that case you can manually add the reference attributes to your schema definition, and mark the relations between them.

**Comment by demopark** [comment]
这里使用schema definition而不是model definition是为了与模型定义本身区分开. references属性引用的model本身就是一个模型定义.而references两个model更多的是一种 schema 的关系.用`架构定义`更贴切也不会与`模型定义`本身冲突.

**Comment by nimingan** [comment]
好的，谢谢你的解释。
