### ISSUE TITLE
sequelize 如何实现分表分库？水平拆分

### ISSUE THREAD

**Issue by zhaitianye** [demopark/sequelize-docs-Zh-CN#45]
如标题描述

**Comment by demopark** [comment]
@zhaitianye sequelize默认不支持sharding. 很难找到一个one-size-fits-all的方式对所有的dialect进行支持. 所以如果数据已经到了需要 sharding 的程度.建议手动对特定的dialect进行处理和优化.

**Comment by zhaitianye** [comment]
@demopark 明白了，谢谢您的解答。
