### ISSUE TITLE
belongsTo创建引用非主键字段的关联

### ISSUE THREAD

**Issue by modenfarmer** [demopark/sequelize-docs-Zh-CN#56]
版本 6.3.4
当用belongsTo关联非主键时,主表总是用自身id,而不用指定的字段

Register.hasOne(User, {as: 'User', foreignKey: 'node'});
User.belongsTo(Register, {targetKey: 'node', foreignKey: 'node'});

两个表node字段名称相同

**Comment by demopark** [comment]
@modenfarmer 
https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/core-concepts/assocs.md#%E5%AF%B9%E4%BA%8E-belongsto-%E5%85%B3%E7%B3%BB

**Comment by modenfarmer** [comment]
非常感谢,问题已解决

**Comment by lfp1024** [comment]
> 非常感谢,问题已解决

咋解决的？Mysql 外键必须关联主表主键
