### ISSUE TITLE
如何不处理不在预期内的参数

### ISSUE THREAD

**Issue by changeLong** [demopark/sequelize-docs-Zh-CN#59]
比如数据库里面有 `id`，‘name’ 列;

我们在请求接口的时候可能会带上 杂七乱八的参数 ，比如 t = 123123123;

那么到了查询时，一般会把所有的请求参数都去查询
`async list(params) {
        let result = await this.app.model.xxx.findAll({
            where : {
                ...params
            }
        })
        return result
    }`;

这时就会把 `t` 也作为where请求，因为表里没有 `t`列，会导致接口报错；

当然代码中是可以仅获取要处理的参数，但是一个个写就很麻烦；请问怎么可以优雅得处理不在预期中的参数呢

**Comment by demopark** [comment]
这个问题跟 sequelize 没有什么直接关系. 来自 request 的 params 怎么能不经过任何处理直接丢给 ORM 呢, 不需要数据校验/格式校验/数据转义以及放注入处理吗?  建议在 controller 层处理成预期内容的对象传递给 model 层的 sequelize.
