### ISSUE TITLE
事务指南页面找不到

### ISSUE THREAD

**Issue by DanielZhui** [demopark/sequelize-docs-Zh-CN#60]
**当前使用的 Node.js 版本 (node -v)**
(可用 node -v 命令 查看)

**当前使用的 sequelize 版本**
(package.json 所指定的版本)

**问题描述**
(描述出现的或寻求解决的问题)

**代码片段**
```
// 相关代码或报错信息
```
[事务指南](https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/core-concepts/other-topics/transactions.md)

**Comment by demopark** [comment]
@DanielZhui 已经修复,谢谢
