### ISSUE TITLE
感觉这迁移功能有点鸡肋啊

### ISSUE THREAD

**Issue by barbecue-pan** [demopark/sequelize-docs-Zh-CN#65]
**当前使用的 Node.js 版本 (node -v)**
14.16.1

**当前使用的 sequelize 版本**
6.0.0

**问题描述**
使用过python的orm，它可以根据model文件自动生成迁移文件并且迁移
而sequelize好像并不支持这样做，还要手写model文件以及迁移文件 特别是model文件有更改的时候 

**代码片段**
```
// 相关代码或报错信息
```

**Comment by demopark** [comment]
@barbecue-pan `Migrations` 即迁移功能描述非常明确--就像你使用版本控制 如 Git 来管理源代码的更改一样,你可以使用迁移来跟踪数据库的更改. 通过迁移,你可以将现有的数据库转移到另一个状态,反之亦然:这些状态转换将保存在迁移文件中,它们描述了如何进入新状态以及如何还原更改以恢复旧状态.

你所描述的`它可以根据model文件自动生成迁移文件并且迁移`,并不是Migrations的功能, 而是[sequelize-auto](https://github.com/sequelize/sequelize-auto)的功能. 它可以将数据库中的表以及表后续的修改直接自动生成sequelize models定义.

简而言之两个出发角度, Migrations是由sequelize model 定义为出发点. 来构建数据库结构并管理其状态; 而 sequelize-auto 是由数据表结构为出发点, 来构建sequelize models 并管理其内容
