### ISSUE TITLE
原始查询中如何使用事务

### ISSUE THREAD

**Issue by qq578023708** [demopark/sequelize-docs-Zh-CN#72]
**当前使用的 Node.js 版本 (node -v)**
(可用 node -v 命令 查看)

**当前使用的 sequelize 版本**
(package.json 所指定的版本)

**问题描述**
(描述出现的或寻求解决的问题)
在原始查询中如何使用事务？
`js
Sequelize.query('INSERT INTO TABLE')
`

**代码片段**
```
// 相关代码或报错信息
```

**Comment by richex-cn** [comment]
See https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-method-query

For example:

```
const t = await sequelize.transaction();
sequelize.query('SELECT * FROM table;', { transaction: t })
```
