### ISSUE TITLE
文档中的链接失效

### ISSUE THREAD

**Issue by Chen-913** [demopark/sequelize-docs-Zh-CN#74]
**sequelize 文档版本**
(对应的文档版本)
v7
**sequelize 目录章节**
(对应的目录章节版本)
https://github.com/demopark/sequelize-docs-Zh-CN/blob/master/core-concepts/getting-started.md#%E8%BF%9E%E6%8E%A5%E5%88%B0%E6%95%B0%E6%8D%AE%E5%BA%93
**反馈描述**
点击`API 参考`的链接后，显示 NotFound
![image](https://user-images.githubusercontent.com/72293244/164025211-e2a17dd3-3dc3-4c53-a384-8813be54dc64.png)

**Comment by demopark** [comment]
@Chen-913 Fixed, thanks for issue
